"use client";

import { WorkflowStudio } from "./workflow-studio";
import { SiteSettingsPanel } from "./site-settings";
import { RedirectManager } from "./redirects";
import { ContentImport } from "./content-import";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Status = "draft" | "review" | "scheduled" | "published";
type Article = { id?: number; slug: string; title: string; spot: string; body: string; category: string; status: Status; heroImage: string; imageAlt: string; videoUrl: string; author: string; sourceName: string; sourceUrl: string; seoTitle: string; seoDescription: string; isBreaking: number; isFeatured: number; publishedAt?: number | null; scheduledAt?: number | string | null; updatedAt?: number };
type Stats = { total: number; published: number; draft: number; review: number; scheduled: number };
type Source = { id: number; name: string; url: string; type: string; active: number; lastCheckedAt: number | null };
type Category = { id?: number; name: string; slug: string; description: string; seoTitle: string; seoDescription: string; color: string; navOrder: number; isVisible: number; articleCount?: number };
type Media = { id: number; publicUrl: string; originalName: string; mimeType: string; sizeBytes: number; altText: string; credit: string; createdAt: number };
type Role = "admin" | "publisher" | "editor" | "reporter" | "viewer";
type AdminUser = { id: number; email: string; fullName: string; role: Role; active: number; mustChangePassword: number; lastLoginAt: number | null; createdAt: number };
type Tab = "dashboard" | "studio" | "articles" | "editor" | "categories" | "media" | "sources" | "users" | "settings" | "redirects" | "import";

const statusLabels: Record<Status, string> = { draft: "Taslak", review: "Editör incelemesi", scheduled: "Planlandı", published: "Yayında" };
const roleLabels: Record<Role, string> = { admin: "Yönetici", publisher: "Yayın Yönetmeni", editor: "Editör", reporter: "Muhabir", viewer: "Görüntüleyici" };
const emptyArticle: Article = { slug: "", title: "", spot: "", body: "", category: "Gündem", status: "draft", heroImage: "/news/gundem.jpg", imageAlt: "", videoUrl: "", author: "Koza TV Haber Merkezi", sourceName: "Koza TV", sourceUrl: "", seoTitle: "", seoDescription: "", isBreaking: 0, isFeatured: 0, scheduledAt: null };
const emptyCategory: Category = { name: "", slug: "", description: "", seoTitle: "", seoDescription: "", color: "#c92721", navOrder: 100, isVisible: 1 };

function relativeDate(value?: number | null) { if (!value) return "Henüz yayınlanmadı"; return new Intl.DateTimeFormat("tr-TR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(value); }
function formatBytes(value: number) { if (value < 1024 * 1024) return `${Math.max(1, Math.round(value / 1024))} KB`; return `${(value / 1024 / 1024).toFixed(1)} MB`; }

export function AdminPanel({ currentUser }: { currentUser: AdminUser }) {
  const [tab, setTab] = useState<Tab>("dashboard");
  const [articles, setArticles] = useState<Article[]>([]);
  const [sources, setSources] = useState<Source[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [media, setMedia] = useState<Media[]>([]);
  const [mediaStats, setMediaStats] = useState({ total: 0, totalBytes: 0, quotaBytes: 10 * 1024 * 1024 * 1024 });
  const [stats, setStats] = useState<Stats>({ total: 0, published: 0, draft: 0, review: 0, scheduled: 0 });
  const [form, setForm] = useState<Article>(emptyArticle);
  const [categoryForm, setCategoryForm] = useState<Category>(emptyCategory);
  const [uploadMeta, setUploadMeta] = useState({ altText: "", credit: "" });
  const [filter, setFilter] = useState<Status | "all">("all");
  const [message, setMessage] = useState("");
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [mediaPickerOpen, setMediaPickerOpen] = useState(false);
  const [sourceForm, setSourceForm] = useState({ name: "", url: "", type: "website" });
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [userForm, setUserForm] = useState({ fullName: "", email: "", role: "editor" as Role, password: "" });

  const refresh = useCallback(async () => {
    const [articleResponse, sourceResponse, categoryResponse, mediaResponse, userResponse] = await Promise.all([fetch("/api/articles"), fetch("/api/sources"), fetch("/api/categories"), fetch("/api/media"), currentUser.role === "admin" ? fetch("/api/users") : Promise.resolve(null)]);
    const [articleData, sourceData, categoryData, mediaData, userData] = await Promise.all([articleResponse.json(), sourceResponse.json(), categoryResponse.json(), mediaResponse.json(), userResponse?.json() ?? Promise.resolve({ users: [] })]);
    setArticles(articleData.articles ?? []); setStats(articleData.stats ?? { total: 0, published: 0, draft: 0, review: 0, scheduled: 0 });
    setSources(sourceData.sources ?? []); setCategories(categoryData.categories ?? []); setMedia(mediaData.media ?? []); setMediaStats(mediaData.stats ?? { total: 0, totalBytes: 0, quotaBytes: 10 * 1024 * 1024 * 1024 });
    setUsers(userData.users ?? []);
  }, [currentUser.role]);

  useEffect(() => { const timer = window.setTimeout(() => refresh().catch(() => setMessage("İçerik verileri alınamadı.")), 0); return () => window.clearTimeout(timer); }, [refresh]);

  const visibleArticles = useMemo(() => filter === "all" ? articles : articles.filter((article) => article.status === filter), [articles, filter]);
  const reviewQueue = articles.filter((article) => article.status === "review").slice(0, 4);
  function update<K extends keyof Article>(key: K, value: Article[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function newArticle() { setForm({ ...emptyArticle, category: categories.find((category) => category.isVisible)?.name || "Gündem" }); setErrors({}); setMessage(""); setTab("editor"); }
  function editArticle(article: Article) { setForm({ ...article, scheduledAt: article.scheduledAt ? new Date(Number(article.scheduledAt)).toISOString().slice(0, 16) : null }); setErrors({}); setMessage(""); setTab("editor"); }

  async function saveArticle(status: Status) {
    setSaving(true); setErrors({}); setMessage("Kaydediliyor…");
    const response = await fetch("/api/articles", { method: form.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, status }) });
    const data = await response.json(); setSaving(false);
    if (!response.ok) { setErrors(data.fields ?? {}); setMessage(data.error ?? "Haber kaydedilemedi"); return; }
    setForm(data.article); setMessage(status === "published" ? "Haber yayına alındı." : status === "review" ? "Haber editör incelemesine gönderildi." : status === "scheduled" ? "Haber planlandı." : "Taslak kaydedildi."); await refresh();
  }

  async function saveCategory(event: FormEvent) {
    event.preventDefault(); setSaving(true); setMessage("Kategori kaydediliyor…");
    const response = await fetch("/api/categories", { method: categoryForm.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(categoryForm) });
    const data = await response.json(); setSaving(false);
    if (!response.ok) { setMessage(data.error ?? "Kategori kaydedilemedi."); return; }
    setCategoryForm(emptyCategory); setMessage("Kategori menü ve haber editöründe güncellendi."); await refresh();
  }

  async function uploadImage(file: File, useForArticle = false) {
    setSaving(true); setMessage("Görsel güvenli biçimde yükleniyor…");
    const payload = new FormData(); payload.set("file", file); payload.set("altText", useForArticle ? form.imageAlt : uploadMeta.altText); payload.set("credit", uploadMeta.credit);
    const response = await fetch("/api/media", { method: "POST", body: payload }); const data = await response.json(); setSaving(false);
    if (!response.ok) { setMessage(data.error ?? "Görsel yüklenemedi."); return; }
    if (useForArticle) setForm((current) => ({ ...current, heroImage: data.media.publicUrl, imageAlt: current.imageAlt || data.media.altText || file.name }));
    setUploadMeta({ altText: "", credit: "" }); setMessage(`${file.name} medya kütüphanesine eklendi.`); await refresh();
  }

  async function addSource(event: FormEvent) { event.preventDefault(); setMessage("Kaynak ekleniyor…"); const response = await fetch("/api/sources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(sourceForm) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "Kaynak eklenemedi"); return; } setSourceForm({ name: "", url: "", type: "website" }); setMessage("Kaynak izleme listesine eklendi."); await refresh(); }

  async function addUser(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage("Kullanıcı oluşturuluyor…"); const response = await fetch("/api/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(userForm) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error ?? "Kullanıcı oluşturulamadı."); return; } setUserForm({ fullName: "", email: "", role: "editor", password: "" }); setMessage("Kullanıcı oluşturuldu; ilk girişte parola değişikliği zorunlu."); await refresh(); }

  async function updateUser(id: number, changes: { role?: Role; active?: boolean }) {
    setSaving(true); setMessage("Kullanıcı güncelleniyor…");
    const response = await fetch("/api/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, ...changes }) });
    const data = await response.json(); setSaving(false);
    if (!response.ok) { setMessage(data.error ?? "Kullanıcı güncellenemedi."); return; }
    setMessage(changes.active === false ? "Kullanıcı pasife alındı ve oturumu kapatıldı." : changes.active === true ? "Kullanıcı yeniden aktif edildi." : "Kullanıcı rolü güncellendi."); await refresh();
  }

  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); window.location.assign("/admin/giris"); }

  const canEdit = currentUser.role !== "viewer";
  const canPublish = currentUser.role === "admin" || currentUser.role === "publisher";
  const tabs: { id: Tab; label: string; icon: string; count?: number }[] = [
    { id: "dashboard", label: "Haber Masası", icon: "▦" }, { id: "studio", label: "Yayın Stüdyosu", icon: "◆", count: stats.review }, { id: "articles", label: "Tüm Haberler", icon: "▤", count: stats.total },
    ...(canEdit ? [{ id: "editor" as Tab, label: "Yeni Haber", icon: "+" }, { id: "media" as Tab, label: "Medya Kütüphanesi", icon: "▧", count: media.length }] : []),
    ...(canPublish ? [{ id: "categories" as Tab, label: "Kategoriler", icon: "≡", count: categories.length }, { id: "sources" as Tab, label: "Kaynak Merkezi", icon: "⌁", count: sources.length }] : []),
    ...(currentUser.role === "admin" ? [{ id: "users" as Tab, label: "Kullanıcılar", icon: "♙", count: users.length }] : []),
    { id: "settings", label: "Site Ayarları", icon: "⚙" }, { id: "redirects", label: "Adres Yönetimi", icon: "⇄" }, { id: "import", label: "İçerik Aktarımı", icon: "⇩" },
  ];
  const title = tab === "import" ? "Eski Site İçerik Aktarımı" : tab === "settings" ? "Site Ayarları" : tab === "redirects" ? "Adres ve Yönlendirme Yönetimi" : tab === "dashboard" ? `Günaydın, ${currentUser.fullName.split(" ")[0]}` : tab === "studio" ? "Profesyonel Yayın Stüdyosu" : tab === "articles" ? "Haber Arşivi" : tab === "editor" ? (form.id ? "Haberi Düzenle" : "Yeni Haber Oluştur") : tab === "categories" ? "Kategori Yönetimi" : tab === "media" ? "Medya Kütüphanesi" : tab === "users" ? "Kullanıcı ve Rol Yönetimi" : "Kaynak Merkezi";

  return <main className="newsroom-shell">
    <aside className="newsroom-side"><a className="admin-logo" href="/"><img src="/koza-logo.png" alt="Koza TV" /></a><span className="workspace-label">YAYIN OPERASYONU</span><nav aria-label="Yönetim bölümleri">{tabs.map((item) => <button className={tab === item.id ? "active" : ""} onClick={() => item.id === "editor" ? newArticle() : setTab(item.id)} type="button" key={item.id}><i>{item.icon}</i>{item.label}{item.count !== undefined && <small>{item.count}</small>}</button>)}</nav><div className="newsroom-ai"><span>AI HABER MASASI</span><strong>Editör kontrolü açık</strong><p>AI taslakları onay olmadan yayınlanamaz.</p></div><a className="back-site" href="/">← Siteye dön</a></aside>
    <section className="newsroom-main"><header className="newsroom-top"><div><span>KOZA TV / İÇERİK MERKEZİ</span><h1>{title}</h1><p>{tab === "import" ? "kozatv.com.tr arşivini yeni siteye taşıyın; eski adresler otomatik yönlendirilir." : tab === "settings" ? "Canlı yayın kaynağı, sosyal hesaplar, künye ve yayın akışını buradan yönetin." : tab === "redirects" ? "Eski site adreslerini yeni adreslere eşleyerek arama motoru değerini koruyun." : tab === "studio" ? "Görevlendirme, blok içerik, revizyon ve yayın onayını tek ekrandan yönetin." : tab === "categories" ? "Menü yapısını, kategori sırasını ve SEO bilgilerini yönetin." : tab === "media" ? "Kalıcı görselleri, alt metinleri ve kullanım alanını yönetin." : tab === "users" ? "Ekip hesaplarını ve yayın yetkilerini güvenle yönetin." : tab === "editor" ? "İçerik, medya, kaynak ve SEO alanlarını birlikte hazırlayın." : "Koza TV yayın operasyonu"}</p></div><div className="newsroom-user"><b>{currentUser.fullName.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</b><span>{currentUser.fullName}<small>{roleLabels[currentUser.role]}</small></span><button type="button" onClick={logout}>Çıkış</button></div></header>
      {message && <div className={message.includes("alınamadı") || message.includes("edilemedi") || message.includes("yüklenemedi") ? "newsroom-message error" : "newsroom-message"}>{message}<button onClick={() => setMessage("")} aria-label="Mesajı kapat">×</button></div>}

      {tab === "studio" && <WorkflowStudio role={currentUser.role} />}

      {tab === "settings" && <SiteSettingsPanel canEdit={canPublish} />}

      {tab === "redirects" && <RedirectManager canEdit={canPublish} />}

      {tab === "import" && <ContentImport canEdit={canPublish} />}

      {tab === "dashboard" && <><div className="newsroom-stats"><article><span>Yayındaki Haber</span><strong>{stats.published}</strong><small>Toplam {stats.total} kayıt</small></article><article><span>Editör Kuyruğu</span><strong>{stats.review}</strong><small>Onay bekleyen içerik</small></article><article><span>Aktif Kategori</span><strong>{categories.filter((item) => item.isVisible).length}</strong><small>Menüde görünür</small></article><article className="accent"><span>Medya Alanı</span><strong>{formatBytes(mediaStats.totalBytes)}</strong><small>{mediaStats.total} kalıcı görsel</small></article></div><div className="newsroom-grid"><section className="newsroom-card desk-list"><div className="card-title"><div><span>EDİTÖR KUYRUĞU</span><h2>İnceleme bekleyenler</h2></div><button onClick={() => setTab("articles")}>Tüm haberler →</button></div>{reviewQueue.length ? reviewQueue.map((article) => <button className="queue-row" onClick={() => editArticle(article)} key={article.id}><img src={article.heroImage} alt="" /><span><b>{article.category}</b><strong>{article.title}</strong><small>{article.author} · {relativeDate(article.updatedAt)}</small></span><i>İncele →</i></button>) : <div className="empty-state">İnceleme kuyruğu temiz.</div>}</section><aside className="newsroom-card today-flow"><div className="card-title"><div><span>BUGÜN</span><h2>Yayın akışı</h2></div></div>{articles.slice(0, 6).map((article) => <div className="today-row" key={article.id}><time>{relativeDate(article.publishedAt ?? article.updatedAt).split(" ").slice(-1)}</time><span><b className={`status status-${article.status}`}>{statusLabels[article.status]}</b><p>{article.title}</p></span></div>)}</aside></div></>}

      {tab === "articles" && <section className="newsroom-card archive"><div className="archive-toolbar"><div>{(["all", "published", "review", "scheduled", "draft"] as const).map((value) => <button className={filter === value ? "active" : ""} onClick={() => setFilter(value)} key={value}>{value === "all" ? "Tümü" : statusLabels[value]}</button>)}</div>{canEdit && <button className="primary" onClick={newArticle}>+ Yeni haber</button>}</div><div className="article-table"><div className="table-head"><span>Haber</span><span>Durum</span><span>Kaynak</span><span>Güncelleme</span><span /></div>{visibleArticles.map((article) => <button className="table-row" onClick={() => canEdit ? editArticle(article) : undefined} key={article.id}><span className="article-cell"><img src={article.heroImage} alt="" /><span><b>{article.category}</b><strong>{article.title}</strong></span></span><span><i className={`status status-${article.status}`}>{statusLabels[article.status]}</i></span><span>{article.sourceName}</span><span>{relativeDate(article.updatedAt)}</span><span>{canEdit ? "→" : ""}</span></button>)}</div></section>}

      {tab === "editor" && <div className="editor-layout"><section className="editor-form"><div className="editor-section"><div className="editor-section-head"><span>01</span><div><h2>Haber içeriği</h2><p>Başlık, spot ve haber metnini hazırlayın.</p></div></div><label>Haber başlığı <small>{form.title.length}/110</small><input value={form.title} maxLength={110} onChange={(event) => update("title", event.target.value)} placeholder="Okurun haberi tek bakışta anlayacağı güçlü başlık" />{errors.title && <em>{errors.title}</em>}</label><label>Spot / kısa özet <small>{form.spot.length}/240</small><textarea value={form.spot} maxLength={240} rows={3} onChange={(event) => update("spot", event.target.value)} placeholder="Haberin en önemli bilgisini iki cümlede özetleyin" />{errors.spot && <em>{errors.spot}</em>}</label><label>Haber metni <textarea className="body-editor" value={form.body} rows={14} onChange={(event) => update("body", event.target.value)} placeholder="Haber metnini paragraflar halinde yazın…" />{errors.body && <em>{errors.body}</em>}</label></div>
        <div className="editor-section"><div className="editor-section-head"><span>02</span><div><h2>Medya ve kaynak</h2><p>Sunucuya yüklenen görseli ve doğrulama kaynağını tanımlayın.</p></div></div><div className="media-editor-actions"><label className="upload-inline">↑ Bilgisayardan görsel yükle<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={saving} onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadImage(file, true); }} /></label><button type="button" onClick={() => setMediaPickerOpen(!mediaPickerOpen)}>▧ Kütüphaneden seç</button><small>JPG, PNG, WebP veya GIF · en fazla 12 MB</small></div>{mediaPickerOpen && <div className="media-picker">{media.slice(0, 12).map((item) => <button type="button" className={form.heroImage === item.publicUrl ? "selected" : ""} onClick={() => { setForm((current) => ({ ...current, heroImage: item.publicUrl, imageAlt: current.imageAlt || item.altText })); setMediaPickerOpen(false); }} key={item.id}><img src={item.publicUrl} alt={item.altText} /><span>{item.originalName}</span></button>)}</div>}<div className="form-grid"><label>Kapak görseli yolu<input value={form.heroImage} onChange={(event) => update("heroImage", event.target.value)} /></label><label>Görsel alternatif metni<input value={form.imageAlt} onChange={(event) => update("imageAlt", event.target.value)} placeholder="Görselde ne var?" /></label><label>Kaynak adı<input value={form.sourceName} onChange={(event) => update("sourceName", event.target.value)} /></label><label>Kaynak URL<input value={form.sourceUrl} onChange={(event) => update("sourceUrl", event.target.value)} placeholder="https://" />{errors.sourceUrl && <em>{errors.sourceUrl}</em>}</label><label>Video URL<input value={form.videoUrl} onChange={(event) => update("videoUrl", event.target.value)} placeholder="YouTube, Vimeo veya HLS adresi" /></label><label>Yazar / servis<input value={form.author} onChange={(event) => update("author", event.target.value)} /></label></div></div>
        <div className="editor-section"><div className="editor-section-head"><span>03</span><div><h2>Yayın ve SEO</h2><p>Kategori, görünürlük ve arama alanlarını kontrol edin.</p></div></div><div className="form-grid"><label>Kategori<select value={form.category} onChange={(event) => update("category", event.target.value)}>{categories.map((category) => <option value={category.name} key={category.id}>{category.name}{category.isVisible ? "" : " (gizli)"}</option>)}</select></label><label>Planlanan tarih<input type="datetime-local" value={typeof form.scheduledAt === "string" ? form.scheduledAt : ""} onChange={(event) => update("scheduledAt", event.target.value)} />{errors.scheduledAt && <em>{errors.scheduledAt}</em>}</label><label className="wide">SEO başlığı<input value={form.seoTitle} onChange={(event) => update("seoTitle", event.target.value)} placeholder="Boş bırakılırsa haber başlığı kullanılır" /></label><label className="wide">SEO açıklaması<textarea rows={2} value={form.seoDescription} onChange={(event) => update("seoDescription", event.target.value)} placeholder="Boş bırakılırsa spot kullanılır" /></label></div><div className="editor-checks"><label><input type="checkbox" checked={Boolean(form.isFeatured)} onChange={(event) => update("isFeatured", event.target.checked ? 1 : 0)} /> Manşette göster</label><label title="Haberi kırmızı şerit, son dakika bandı ve canlı akışta öne çıkarır"><input type="checkbox" checked={Boolean(form.isBreaking)} onChange={(event) => update("isBreaking", event.target.checked ? 1 : 0)} /> Son dakika olarak öne çıkar</label></div></div></section>
        <aside className="editor-aside"><div className="preview-card"><div className="preview-label">CANLI ÖNİZLEME</div><img src={form.heroImage || "/news/gundem.jpg"} alt="" /><span>{form.category}</span><h2>{form.title || "Haber başlığınız burada görünecek"}</h2><p>{form.spot || "Haber spotu kartlarda ve paylaşım alanlarında bu şekilde görünecek."}</p><small>{form.author}</small></div><div className="publish-card"><h3>Yayın kontrolü</h3><ul><li className={form.title.length >= 12 ? "ok" : ""}>Başlık hazır</li><li className={form.spot.length >= 24 ? "ok" : ""}>Spot hazır</li><li className={form.body.length >= 80 ? "ok" : ""}>Haber metni hazır</li><li className={form.imageAlt ? "ok" : ""}>Görsel açıklaması</li><li className={form.sourceName ? "ok" : ""}>Kaynak bilgisi</li></ul><button disabled={saving} onClick={() => saveArticle("published")} className="publish">Şimdi yayınla</button><button disabled={saving} onClick={() => saveArticle("review")}>Editör incelemesine gönder</button><button disabled={saving} onClick={() => saveArticle("scheduled")}>Yayını planla</button><button disabled={saving} onClick={() => saveArticle("draft")}>Taslak kaydet</button>{form.id && form.status === "published" && <a href={`/haber/${form.slug}`} target="_blank" rel="noreferrer">Yayındaki haberi gör →</a>}</div></aside></div>}

      {tab === "categories" && <div className="category-manager"><section className="newsroom-card"><div className="card-title"><div><span>MENÜ MİMARİSİ</span><h2>Tüm kategoriler</h2><p>Sıra numarası küçük olan kategoriler menüde önce görünür.</p></div><button onClick={() => setCategoryForm(emptyCategory)}>+ Yeni kategori</button></div><div className="category-admin-list"><div className="category-admin-head"><span /><span>Kategori</span><span>Haber</span><span>Sıra</span><span>Durum</span><span /></div>{categories.map((category) => <button type="button" onClick={() => setCategoryForm(category)} key={category.id}><i style={{ background: category.color }} /><span><strong>{category.name}</strong><small>/kategori/{category.slug}</small></span><b>{category.articleCount}</b><b>{category.navOrder}</b><em className={category.isVisible ? "visible" : ""}>{category.isVisible ? "Menüde" : "Gizli"}</em><span>→</span></button>)}</div></section><aside className="newsroom-card category-form"><span>{categoryForm.id ? "KATEGORİYİ DÜZENLE" : "YENİ KATEGORİ"}</span><h2>{categoryForm.id ? categoryForm.name : "Kategori oluştur"}</h2><form onSubmit={saveCategory}><label>Kategori adı<input value={categoryForm.name} onChange={(event) => setCategoryForm({ ...categoryForm, name: event.target.value })} placeholder="Örn. Sağlık" /></label><label>URL kısa adı<input value={categoryForm.slug} onChange={(event) => setCategoryForm({ ...categoryForm, slug: event.target.value })} placeholder="Otomatik oluşturulur" /></label><label>Açıklama<textarea rows={3} value={categoryForm.description} onChange={(event) => setCategoryForm({ ...categoryForm, description: event.target.value })} /></label><div className="category-form-pair"><label>Menü sırası<input type="number" value={categoryForm.navOrder} onChange={(event) => setCategoryForm({ ...categoryForm, navOrder: Number(event.target.value) })} /></label><label>Vurgu rengi<input type="color" value={categoryForm.color} onChange={(event) => setCategoryForm({ ...categoryForm, color: event.target.value })} /></label></div><label>SEO başlığı<input value={categoryForm.seoTitle} onChange={(event) => setCategoryForm({ ...categoryForm, seoTitle: event.target.value })} /></label><label>SEO açıklaması<textarea rows={2} value={categoryForm.seoDescription} onChange={(event) => setCategoryForm({ ...categoryForm, seoDescription: event.target.value })} /></label><div className="category-visibility"><input aria-label="Menüde göster" type="checkbox" checked={Boolean(categoryForm.isVisible)} onChange={(event) => setCategoryForm({ ...categoryForm, isVisible: event.target.checked ? 1 : 0 })} /><span><strong>Menüde göster</strong><small>Kapatılırsa kategori URL&apos;si ve menü bağlantısı gizlenir.</small></span></div><button type="submit" disabled={saving}>{saving ? "Kaydediliyor…" : "Kategoriyi kaydet"}</button></form></aside></div>}

      {tab === "media" && <div className="media-manager"><section className="media-toolbar"><div><span>KALICI DEPOLAMA</span><strong>{formatBytes(mediaStats.totalBytes)} / {formatBytes(mediaStats.quotaBytes)}</strong><small>{mediaStats.total} görsel · diskte en az 1 GB boş alan korunur</small></div><label>Görsel alternatif metni<input value={uploadMeta.altText} onChange={(event) => setUploadMeta({ ...uploadMeta, altText: event.target.value })} placeholder="Görselde ne var?" /></label><label>Fotoğraf / ajans kredisi<input value={uploadMeta.credit} onChange={(event) => setUploadMeta({ ...uploadMeta, credit: event.target.value })} placeholder="Koza TV / AA / DHA…" /></label><label className="media-upload-button">↑ Yeni görsel yükle<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={saving} onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadImage(file); }} /></label></section><section className="media-library-grid">{media.length ? media.map((item) => <article key={item.id}><div><img src={item.publicUrl} alt={item.altText} /><button type="button" onClick={() => { setForm((current) => ({ ...current, heroImage: item.publicUrl, imageAlt: current.imageAlt || item.altText })); setTab("editor"); }}>Haberde kullan</button></div><strong>{item.originalName}</strong><p>{item.altText || "Alt metin girilmemiş"}</p><small>{formatBytes(item.sizeBytes)} · {item.credit || "Kredi belirtilmemiş"}</small></article>) : <div className="media-empty"><span>▧</span><h2>Medya kütüphanesi boş</h2><p>İlk görseli yüklediğinizde dosya kalıcı sunucu alanına kaydedilecek.</p></div>}</section></div>}

      {tab === "sources" && <div className="sources-layout"><section className="newsroom-card"><div className="card-title"><div><span>KAYNAK HAVUZU</span><h2>İzlenen yayınlar</h2><p>Haberler doğrudan yayınlanmaz; önce editör kuyruğuna taslak olarak gelir.</p></div></div><div className="source-list">{sources.map((source) => <article key={source.id}><span className="source-icon">⌁</span><div><strong>{source.name}</strong><a href={source.url} target="_blank" rel="noreferrer">{source.url}</a></div><i>{source.type === "official" ? "RESMÎ KAYNAK" : "WEB SİTESİ"}</i><b className={source.active ? "online" : ""}>{source.active ? "İzleniyor" : "Kapalı"}</b></article>)}</div></section><aside className="newsroom-card source-add"><span>YENİ KAYNAK</span><h2>URL ile kaynak ekle</h2><p>RSS, ajans veya resmî kurum adresini tanımlayın. İçerikler editör kuyruğuna alınır.</p><form onSubmit={addSource}><label>Kaynak adı<input value={sourceForm.name} onChange={(event) => setSourceForm({ ...sourceForm, name: event.target.value })} /></label><label>Kaynak adresi<input type="url" value={sourceForm.url} onChange={(event) => setSourceForm({ ...sourceForm, url: event.target.value })} placeholder="https://" /></label><label>Kaynak türü<select value={sourceForm.type} onChange={(event) => setSourceForm({ ...sourceForm, type: event.target.value })}><option value="website">Web sitesi</option><option value="rss">RSS</option><option value="official">Resmî kaynak</option><option value="agency">Haber ajansı</option></select></label><button type="submit">Kaynağı ekle</button></form><div className="ai-note"><strong>AI güvenlik kuralı</strong><p>Kaynak ve editör onayı olmayan taslaklar yayınlanamaz.</p></div></aside></div>}

      {tab === "users" && currentUser.role === "admin" && <div className="users-layout"><section className="newsroom-card"><div className="card-title"><div><span>EKİP ERİŞİMİ</span><h2>Yetkili kullanıcılar</h2><p>Her hesap yalnızca rolüne tanımlı işlemleri yapabilir.</p></div></div><div className="user-list"><div className="user-list-head"><span>Kullanıcı</span><span>Rol</span><span>Son giriş</span><span>Durum</span></div>{users.map((user) => <article key={user.id}><div className="user-identity"><b>{user.fullName.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</b><span><strong>{user.fullName}</strong><small>{user.email}</small></span></div>{user.id === currentUser.id ? <em>{roleLabels[user.role]} (siz)</em> : <label className="user-role-select"><span className="visually-hidden">{user.fullName} rolü</span><select value={user.role} disabled={saving} onChange={(event) => void updateUser(user.id, { role: event.target.value as Role })}>{(Object.keys(roleLabels) as Role[]).map((role) => <option value={role} key={role}>{roleLabels[role]}</option>)}</select></label>}<time>{user.lastLoginAt ? relativeDate(user.lastLoginAt) : "Henüz giriş yapmadı"}</time><div className="user-state"><i className={user.active ? "active" : ""}>{user.mustChangePassword ? "Parola bekliyor" : user.active ? "Aktif" : "Kapalı"}</i>{user.id !== currentUser.id && <button type="button" disabled={saving} onClick={() => void updateUser(user.id, { active: !user.active })}>{user.active ? "Pasife al" : "Aktif et"}</button>}</div></article>)}</div></section><aside className="newsroom-card user-add"><span>YENİ KULLANICI</span><h2>Ekip hesabı aç</h2><p>Geçici parolayı güvenli biçimde kullanıcıya iletin. İlk girişte değiştirmesi zorunludur.</p><form onSubmit={addUser}><label>Ad soyad<input value={userForm.fullName} onChange={(event) => setUserForm({ ...userForm, fullName: event.target.value })} required /></label><label>E-posta<input type="email" value={userForm.email} onChange={(event) => setUserForm({ ...userForm, email: event.target.value })} required /></label><label>Rol<select value={userForm.role} onChange={(event) => setUserForm({ ...userForm, role: event.target.value as Role })}><option value="admin">Yönetici</option><option value="publisher">Yayın Yönetmeni</option><option value="editor">Editör</option><option value="reporter">Muhabir</option><option value="viewer">Görüntüleyici</option></select></label><label>Geçici parola<input type="password" autoComplete="new-password" minLength={12} value={userForm.password} onChange={(event) => setUserForm({ ...userForm, password: event.target.value })} placeholder="12+ karakter, Aa, 1, !" required /></label><button disabled={saving} type="submit">{saving ? "Oluşturuluyor…" : "Kullanıcı oluştur"}</button></form><div className="role-note"><b>Yönetici</b> tüm sistemi; <b>Yayın Yönetmeni</b> yayın ve yapılandırmayı; <b>Editör/Muhabir</b> taslakları; <b>Görüntüleyici</b> yalnızca okumayı yönetir.</div></aside></div>}
    </section>
  </main>;
}
