"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Role = "admin" | "publisher" | "editor" | "reporter" | "viewer";
type BlockType = "paragraph" | "heading" | "quote" | "list" | "image" | "video" | "embed";
type Block = { id: string; type: BlockType; content: string; caption?: string };
type Article = { id: number; title: string; spot: string; body: string; blocks: Block[]; category: string; status: string; workflowState: string; assignedTo: number | null; editVersion: number; heroImage: string; imageAlt: string; sourceName: string; isBreaking: number; isFeatured: number; homepageOrder: number; slug: string; scheduledAt?: number | string | null };
type Timeline = { revisions: { id: number; version: number; actorName: string; createdAt: number }[]; comments: { id: number; authorName: string; body: string; createdAt: number }[]; events: { id: number; toState: string; actorName: string; note: string; createdAt: number }[]; report: { actorName: string; total: number; published: number; approved: number }[]; users: { id: number; fullName: string; role: Role }[] };
const states: Record<string, string> = { reporter_draft: "Muhabir taslağı", editor_review: "Editör kontrolünde", changes_requested: "Değişiklik istendi", approved: "Yayın onaylı", rejected: "Reddedildi", published: "Yayında", withdrawn: "Yayından kaldırıldı" };
const blockLabels: Record<BlockType, string> = { paragraph: "Paragraf", heading: "Ara başlık", quote: "Alıntı", list: "Liste", image: "Görsel", video: "Video", embed: "Sosyal medya" };
const emptyTimeline: Timeline = { revisions: [], comments: [], events: [], report: [], users: [] };
const bodyFromBlocks = (blocks: Block[]) => blocks.filter((block) => !["image", "video", "embed"].includes(block.type)).map((block) => block.content).join("\n\n");
const shortDate = (value: number) => new Intl.DateTimeFormat("tr-TR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(value);
const localDate = (value: Article["scheduledAt"]) => value ? new Date(value).toISOString().slice(0, 16) : "";

export function WorkflowStudio({ role }: { role: Role }) {
  const [articles, setArticles] = useState<Article[]>([]); const [selected, setSelected] = useState<Article | null>(null); const [timeline, setTimeline] = useState<Timeline>(emptyTimeline); const [message, setMessage] = useState(""); const [note, setNote] = useState(""); const [comment, setComment] = useState(""); const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false); const [preview, setPreview] = useState<"desktop" | "mobile">("desktop");
  const canEdit = role !== "viewer"; const canApprove = role === "admin" || role === "publisher";
  const loadTimeline = useCallback(async (id: number) => { const response = await fetch(`/api/editorial?articleId=${id}`); if (response.ok) setTimeline(await response.json()); }, []);
  const load = useCallback(async () => { const response = await fetch("/api/articles?limit=100"); const data = await response.json(); const next = data.articles ?? []; setArticles(next); setSelected((current) => current ? next.find((item: Article) => item.id === current.id) ?? current : next[0] ?? null); }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]); useEffect(() => { if (selected) queueMicrotask(() => void loadTimeline(selected.id)); }, [selected, loadTimeline]);
  async function persist(article: Article, quiet = false) { setSaving(true); const response = await fetch("/api/articles", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...article, body: bodyFromBlocks(article.blocks) }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error ?? "Kayıt başarısız."); if (data.code === "EDIT_CONFLICT") await load(); return; } setSelected(data.article); setDirty(false); setMessage(quiet ? "Otomatik kaydedildi." : `Sürüm ${data.article.editVersion} kaydedildi.`); await Promise.all([load(), loadTimeline(data.article.id)]); }
  // persist intentionally follows the latest selected draft; timer cleanup prevents duplicate autosaves.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (!dirty || !selected || !canEdit) return; const timer = window.setTimeout(() => void persist(selected, true), 4000); return () => window.clearTimeout(timer); }, [dirty, selected, canEdit]);
  function change(patch: Partial<Article>) { setSelected((current) => current ? { ...current, ...patch } : current); setDirty(true); }
  function updateBlock(id: string, patch: Partial<Block>) { if (selected) change({ blocks: selected.blocks.map((block) => block.id === id ? { ...block, ...patch } : block) }); }
  function addBlock(type: BlockType) { if (selected) change({ blocks: [...selected.blocks, { id: crypto.randomUUID(), type, content: "" }] }); }
  function moveBlock(index: number, delta: -1 | 1) { if (!selected) return; const blocks = [...selected.blocks]; const target = index + delta; if (target < 0 || target >= blocks.length) return; [blocks[index], blocks[target]] = [blocks[target], blocks[index]]; change({ blocks }); }
  async function editorial(payload: Record<string, unknown>) { if (!selected) return; setSaving(true); const response = await fetch("/api/editorial", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ articleId: selected.id, ...payload }) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error ?? "İşlem tamamlanamadı."); return; } setNote(""); setMessage("Editoryal işlem kaydedildi."); await Promise.all([load(), loadTimeline(selected.id)]); }
  async function submitComment(event: FormEvent) { event.preventDefault(); await editorial({ type: "comment", note: comment }); setComment(""); }
  const queue = useMemo(() => articles.reduce<Record<string, number>>((all, article) => ({ ...all, [article.workflowState]: (all[article.workflowState] || 0) + 1 }), {}), [articles]);
  if (!selected) return <section className="studio-empty"><h2>Yayın stüdyosu hazırlanıyor</h2></section>;
  return <div className="workflow-studio">
    <aside className="studio-queue"><div className="studio-queue-head"><span>YAYIN KUYRUĞU</span><strong>{articles.length} haber</strong></div><div className="queue-summary"><i>{queue.editor_review || 0}<small>Kontrol</small></i><i>{queue.approved || 0}<small>Onaylı</small></i><i>{queue.changes_requested || 0}<small>Revize</small></i></div><div className="studio-articles">{articles.map((article) => <button className={selected.id === article.id ? "active" : ""} onClick={() => { if (!dirty || window.confirm("Kaydedilmemiş değişikliklerden vazgeçilsin mi?")) { setSelected(article); setDirty(false); } }} key={article.id}><em>{article.category}</em><strong>{article.title}</strong><span>{states[article.workflowState]}<small>v{article.editVersion}</small></span></button>)}</div></aside>
    <section className="studio-canvas"><header><div><span>{states[selected.workflowState]}</span><h2>{selected.title}</h2><p>{dirty ? "Kaydedilmemiş değişiklik var" : `Sürüm ${selected.editVersion} güncel`}</p></div><button disabled={!dirty || saving} onClick={() => void persist(selected)}>{saving ? "Kaydediliyor…" : "Sürümü kaydet"}</button></header>{message && <div className="studio-message">{message}</div>}
      <div className="studio-fields"><label className="wide">Haber başlığı<input disabled={!canEdit} value={selected.title} onChange={(event) => change({ title: event.target.value })} /></label><label className="wide">Spot<textarea disabled={!canEdit} rows={3} value={selected.spot} onChange={(event) => change({ spot: event.target.value })} /></label><label>Kapak görseli<input disabled={!canEdit} value={selected.heroImage} onChange={(event) => change({ heroImage: event.target.value })} /></label><label>Görsel alt metni<input disabled={!canEdit} value={selected.imageAlt} onChange={(event) => change({ imageAlt: event.target.value })} /></label><label>Kaynak<input disabled={!canEdit} value={selected.sourceName} onChange={(event) => change({ sourceName: event.target.value })} /></label><label>Manşet sırası<input disabled={!canEdit} type="number" min="1" max="999" value={selected.homepageOrder ?? 100} onChange={(event) => change({ homepageOrder: Number(event.target.value) })} /></label><label className="studio-check" title="Kırmızı şerit ve son dakika akışında gösterir"><input disabled={!canEdit} type="checkbox" checked={Boolean(selected.isBreaking)} onChange={(event) => change({ isBreaking: event.target.checked ? 1 : 0 })} /> Son dakika olarak öne çıkar</label><label className="studio-check"><input disabled={!canEdit} type="checkbox" checked={Boolean(selected.isFeatured)} onChange={(event) => change({ isFeatured: event.target.checked ? 1 : 0 })} /> Ana sayfa manşeti</label></div>
      <div className="block-toolbar">{(Object.keys(blockLabels) as BlockType[]).map((type) => <button disabled={!canEdit} onClick={() => addBlock(type)} key={type}>+ {blockLabels[type]}</button>)}</div>
      <div className="block-list">{selected.blocks.map((block, index) => <article className={`content-block block-${block.type}`} key={block.id}><div><span>{blockLabels[block.type]}</span><button disabled={index === 0} onClick={() => moveBlock(index, -1)}>↑</button><button disabled={index === selected.blocks.length - 1} onClick={() => moveBlock(index, 1)}>↓</button><button disabled={!canEdit || selected.blocks.length === 1} onClick={() => change({ blocks: selected.blocks.filter((item) => item.id !== block.id) })}>×</button></div><textarea disabled={!canEdit} rows={block.type === "paragraph" ? 6 : 3} value={block.content} placeholder={block.type === "list" ? "Her satıra bir madde" : ["image", "video", "embed"].includes(block.type) ? "Güvenli medya URL'si" : `${blockLabels[block.type]} içeriği`} onChange={(event) => updateBlock(block.id, { content: event.target.value })} />{["image", "video"].includes(block.type) && <input value={block.caption ?? ""} placeholder="Açıklama / kaynak" onChange={(event) => updateBlock(block.id, { caption: event.target.value })} />}</article>)}</div>
      <section className={`studio-preview ${preview}`}><div><span>ÖN İZLEME</span><button className={preview === "desktop" ? "active" : ""} onClick={() => setPreview("desktop")}>Masaüstü</button><button className={preview === "mobile" ? "active" : ""} onClick={() => setPreview("mobile")}>Mobil</button></div><article><img src={selected.heroImage} alt={selected.imageAlt} /><small>{selected.category}</small><h2>{selected.title}</h2><p>{selected.spot}</p></article></section>
    </section>
    <aside className="studio-inspector"><section><span>İŞ AKIŞI</span><h3>{states[selected.workflowState]}</h3><label>Haberi ata<select disabled={!canEdit} value={selected.assignedTo ?? ""} onChange={(event) => void editorial({ type: "workflow", action: "assign", assigneeId: event.target.value ? Number(event.target.value) : null })}><option value="">Atanmamış</option>{timeline.users.filter((user) => user.role !== "viewer").map((user) => <option value={user.id} key={user.id}>{user.fullName} · {user.role}</option>)}</select></label><textarea rows={3} value={note} onChange={(event) => setNote(event.target.value)} placeholder="Değişiklik, ret veya düzeltme gerekçesi" /><div className="workflow-actions">
      {["reporter_draft", "changes_requested", "rejected"].includes(selected.workflowState) && <button disabled={!canEdit} onClick={() => void editorial({ type: "workflow", action: "submit_review", note })}>Editöre gönder</button>}{selected.workflowState === "editor_review" && canEdit && <><button onClick={() => void editorial({ type: "workflow", action: "request_changes", note })}>Değişiklik iste</button><button className="danger" onClick={() => void editorial({ type: "workflow", action: "reject", note })}>Reddet</button></>}{selected.workflowState === "editor_review" && canApprove && <button className="success" onClick={() => void editorial({ type: "workflow", action: "approve", note })}>Yayın onayı ver</button>}{selected.workflowState === "approved" && canApprove && <><button className="publish" onClick={() => void editorial({ type: "workflow", action: "publish", note })}>Şimdi yayınla</button><label>Planlanan tarih<input type="datetime-local" value={localDate(selected.scheduledAt)} onChange={(event) => change({ scheduledAt: event.target.value })} /></label><button onClick={() => selected.scheduledAt ? void persist({ ...selected, status: "scheduled" }) : setMessage("Planlanan tarihi seçin.")}>Yayını planla</button></>}{selected.workflowState === "published" && canEdit && <button onClick={() => void editorial({ type: "workflow", action: "correction", note })}>Düzeltme notu yayınla</button>}{selected.workflowState === "published" && canApprove && <button className="danger" onClick={() => void editorial({ type: "workflow", action: "withdraw", note })}>Yayından kaldır</button>}{["rejected", "withdrawn"].includes(selected.workflowState) && canEdit && <button onClick={() => void editorial({ type: "workflow", action: "reopen", note })}>Taslağa geri aç</button>}</div></section>
      <section><span>YAYIN KONTROLÜ</span><ul className="studio-checklist"><li className={selected.title.length >= 12 ? "ok" : ""}>Başlık</li><li className={selected.spot.length >= 24 ? "ok" : ""}>Spot</li><li className={bodyFromBlocks(selected.blocks).length >= 80 ? "ok" : ""}>Haber metni</li><li className={selected.imageAlt ? "ok" : ""}>Görsel alt metni</li><li className={selected.sourceName ? "ok" : ""}>Kaynak</li></ul></section>
      <section><span>EKİP NOTLARI</span><form onSubmit={submitComment}><textarea rows={3} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Editöre not bırak…" /><button disabled={!canEdit || comment.trim().length < 2}>Not ekle</button></form>{timeline.comments.slice(0, 5).map((item) => <article className="studio-comment" key={item.id}><strong>{item.authorName}</strong><p>{item.body}</p><small>{shortDate(item.createdAt)}</small></article>)}</section>
      <section><span>REVİZYONLAR</span>{timeline.revisions.slice(0, 8).map((item) => <article className="revision-row" key={item.id}><div><strong>v{item.version}</strong><small>{item.actorName} · {shortDate(item.createdAt)}</small></div>{canEdit && <button onClick={() => void editorial({ type: "restore", revisionId: item.id })}>Geri yükle</button>}</article>)}</section>
      <section><span>30 GÜNLÜK OPERASYON</span>{timeline.report.slice(0, 5).map((item) => <article className="report-row" key={item.actorName}><strong>{item.actorName}</strong><small>{item.total} işlem · {item.published} yayın · {item.approved} onay</small></article>)}</section>
      <section><span>İŞLEM GEÇMİŞİ</span>{timeline.events.slice(0, 8).map((item, index) => <article className="event-row" key={`${item.createdAt}-${index}`}><b>{states[item.toState]}</b><small>{item.actorName} · {shortDate(item.createdAt)}</small>{item.note && <p>{item.note}</p>}</article>)}</section>
    </aside>
  </div>;
}
