import assert from "node:assert/strict";
import test from "node:test";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { compilePostgresQuery } from "../db/postgres-adapter.mjs";
import { isUniqueConstraintError } from "../db/error-model.mjs";

const execFileAsync = promisify(execFile);

test("PostgreSQL bağdaştırıcısı konumsal parametreleri ve SQLite arama sözdizimini güvenle çevirir", () => {
  const query = compilePostgresQuery(
    "SELECT title AS articleTitle FROM articles WHERE title LIKE ? ESCAPE '\\' AND instr(koza_search_text(body),?)>0 LIMIT ?",
    ["%Koza%", "haber", 20],
  );
  assert.equal(query.sql, "SELECT title AS \"articleTitle\" FROM articles WHERE title ILIKE $1 ESCAPE '\\' AND strpos(koza_search_text(body),$2)>0 LIMIT $3");
  assert.deepEqual(query.values, ["%Koza%", "haber", 20]);
});

test("PostgreSQL bağdaştırıcısı adlandırılmış ve tekrarlanan parametreleri tek değerle bağlar", () => {
  const query = compilePostgresQuery(
    "UPDATE articles SET agency_received_at=CASE WHEN @sourceId IS NULL THEN NULL WHEN agency_source_id=@sourceId THEN agency_received_at ELSE @now END,updated_at=@now WHERE id=@id",
    [{ sourceId: 4, now: 123456, id: 9 }],
  );
  assert.equal(query.sql, "UPDATE articles SET agency_received_at=CASE WHEN $1 IS NULL THEN NULL WHEN agency_source_id=$1 THEN agency_received_at ELSE $2 END,updated_at=$2 WHERE id=$3");
  assert.deepEqual(query.values, [4, 123456, 9]);
});

test("SQLite çalışma paketi isteğe bağlı pg-native sürücüsünü başlangıçta yüklemez", async () => {
  const adapter = await readFile(new URL("../db/postgres-adapter.mjs", import.meta.url), "utf8");
  assert.match(adapter, /\["pg", "native"\]\.join\("-"\)/);
  assert.match(adapter, /Reflect\.apply\(require, undefined, \[nativeDriverPackage\]\)/);
  assert.doesNotMatch(adapter, /require\("pg-native"\)/);
});

test("PostgreSQL şeması mevcut Koza TV tablolarını, kısıtları ve arama fonksiyonunu kapsar", async () => {
  const schema = await readFile(new URL("../db/postgres-schema.sql", import.meta.url), "utf8");
  for (const table of ["articles", "categories", "media_assets", "admin_users", "admin_sessions", "article_revisions", "workflow_events", "audit_logs", "site_settings", "redirects", "import_items", "agency_items", "advertisements"]) {
    assert.match(schema, new RegExp(`CREATE TABLE ${table} \\(`));
  }
  assert.match(schema, /CREATE OR REPLACE FUNCTION koza_search_text/);
  assert.match(schema, /GENERATED BY DEFAULT AS IDENTITY/);
  assert.doesNotMatch(schema, /AUTOINCREMENT|PRAGMA|sqlite_master|typeof\(/i);
});

test("SQLite → PostgreSQL aktarımı hedefi sessizce silmez ve her tabloyu sayarak doğrular", async () => {
  const script = await readFile(new URL("../scripts/migrate-sqlite-to-postgres.mjs", import.meta.url), "utf8");
  assert.match(script, /Hedef veritabanı boş değil/);
  assert.match(script, /SQLite bütünlük kontrolü başarısız/);
  assert.match(script, /mkdtemp\(join\(tmpdir\(\), "kozatv-sqlite-migration-"\)\)/);
  assert.match(script, /new URL\("\.\.\/db\/postgres-schema\.sql", import\.meta\.url\)/);
  assert.match(script, /rm\(workingDirectory, \{ recursive: true, force: true \}\)/);
  assert.match(script, /satır sayısı uyuşmuyor/);
  assert.match(script, /BEGIN/);
  assert.match(script, /COMMIT/);
  assert.match(script, /ROLLBACK/);
  assert.doesNotMatch(script, /DROP\s+(DATABASE|SCHEMA|TABLE)|TRUNCATE/i);
});

test("PostgreSQL canlı yazma testi yalnız loopback ve açık onayla çalışır; geçici verisini temizler", async () => {
  const script = await readFile(new URL("../scripts/smoke-postgres.mjs", import.meta.url), "utf8");
  assert.match(script, /KOZA_ALLOW_WRITE_SMOKE/);
  assert.match(script, /127\.0\.0\.1/);
  assert.match(script, /localhost/);
  assert.match(script, /DELETE FROM redirects WHERE from_path/);
  assert.match(script, /PostgreSQL haber yazma smoke testi/);
  assert.match(script, /hiddenDraft\.status !== 404/);
  assert.match(script, /DELETE FROM articles WHERE id/);
  assert.match(script, /DELETE FROM audit_logs WHERE actor/);
  assert.match(script, /DELETE FROM admin_users WHERE email/);
  assert.doesNotMatch(script, /console\.log\([^\n]*(password|cookie|email)/i);
});

test("tam PostgreSQL üretim doğrulaması yalnız izole kopyada çalışır ve kritik yönetim akışlarını kapsar", async () => {
  const script = await readFile(new URL("../scripts/verify-postgres-production.mjs", import.meta.url), "utf8");
  assert.match(script, /KOZA_ALLOW_DESTRUCTIVE_VERIFY/);
  assert.match(script, /\^kozatv_verify_/);
  assert.match(script, /127\.0\.0\.1/);
  for (const path of ["/api/auth/login", "/api/articles", "/api/categories", "/api/media", "/api/editorial", "/api/ads", "/api/settings", "/api/users"]) {
    assert.match(script, new RegExp(path.replaceAll("/", "\\/")));
  }
  assert.match(script, /five-failure account lock/);
  assert.match(script, /PostgreSQL relational persistence/);
  assert.doesNotMatch(script, /DROP\s+(DATABASE|SCHEMA|TABLE)|TRUNCATE/i);
});

test("benzersizlik hataları SQLite ve PostgreSQL için aynı 409 sözleşmesine çevrilir", () => {
  assert.equal(isUniqueConstraintError(new Error("UNIQUE constraint failed: categories.slug")), true);
  assert.equal(isUniqueConstraintError(Object.assign(new Error("duplicate key value violates unique constraint"), { code: "23505" })), true);
  assert.equal(isUniqueConstraintError(new Error("connection refused")), false);
});

test("haber yazma sorguları PostgreSQL'de boş ajans alanlarının sayısal türünü açıkça korur", async () => {
  const database = await readFile(new URL("../db/index.ts", import.meta.url), "utf8");
  assert.match(database, /CAST\(@agencySourceId AS INTEGER\) IS NULL/);
  assert.match(database, /ELSE CAST\(@now AS BIGINT\) END/);
  assert.match(database, /withdrawn_at=CASE WHEN \?='withdrawn' THEN CAST\(\? AS BIGINT\)/);
  assert.match(database, /COALESCE\(published_at,CAST\(\? AS BIGINT\)\)/);
});

test("Radore yayını PostgreSQL'i dışarı açmaz; doğrulamalı yedek ve gerçek geri yükleme testi kurar", async () => {
  const service = await readFile(new URL("../deployment/radore/kozatv.service", import.meta.url), "utf8");
  const environment = await readFile(new URL("../deployment/radore/app.env.example", import.meta.url), "utf8");
  const backup = await readFile(new URL("../deployment/radore/kozatv-postgres-backup", import.meta.url), "utf8");
  const restore = await readFile(new URL("../deployment/radore/kozatv-postgres-restore-test", import.meta.url), "utf8");
  const health = await readFile(new URL("../deployment/radore/kozatv-postgres-health", import.meta.url), "utf8");
  const healthService = await readFile(new URL("../deployment/radore/kozatv-postgres-health.service", import.meta.url), "utf8");
  const healthTimer = await readFile(new URL("../deployment/radore/kozatv-postgres-health.timer", import.meta.url), "utf8");
  const sshHardening = await readFile(new URL("../deployment/radore/sshd-hardening.conf", import.meta.url), "utf8");
  const knownHosts = await readFile(new URL("../deployment/radore/known_hosts", import.meta.url), "utf8");
  const readme = await readFile(new URL("../deployment/radore/README.md", import.meta.url), "utf8");

  assert.match(service, /User=kozatv/);
  assert.match(service, /Environment=KOZA_WORKERS=6/);
  assert.match(service, /scripts\/start-cluster\.mjs/);
  assert.match(service, /EnvironmentFile=\/etc\/kozatv\/app\.env/);
  assert.match(service, /NoNewPrivileges=true/);
  assert.match(service, /CapabilityBoundingSet=\n/);
  assert.match(service, /PrivateDevices=true/);
  assert.match(service, /ProtectKernelLogs=true/);
  assert.match(service, /RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6/);
  assert.match(service, /RestrictNamespaces=true/);
  assert.match(service, /UMask=0077/);
  assert.match(environment, /postgresql:\/\/\/kozatv\?host=%2Fvar%2Frun%2Fpostgresql/);
  assert.doesNotMatch(environment, /password=/i);
  assert.match(backup, /pg_dump/);
  assert.doesNotMatch(backup, /\/dev\/stdout/);
  assert.match(backup, /pg_restore --list/);
  assert.match(backup, /media\.tar\.gz/);
  assert.match(backup, /sha256sum/);
  assert.match(backup, /Güvensiz yedek dizini reddedildi/);
  assert.match(restore, /createdb --owner=kozatv/);
  assert.match(restore, /pg_restore --exit-on-error[^\n]+< kozatv\.dump/);
  assert.match(restore, /Güvensiz yedek dizini reddedildi/);
  assert.match(restore, /dropdb --if-exists/);
  assert.match(health, /pg_isready/);
  assert.match(health, /systemctl is-active --quiet postgresql\.service/);
  assert.match(health, /media_files >= media_count/);
  assert.match(health, /max_backup_age_minutes/);
  assert.match(health, /auth_status.*401/);
  assert.match(health, /system-health\.json/);
  assert.match(health, /latestBackupAt/);
  assert.match(health, /install -o kozatv -g kozatv -m 0600/);
  assert.match(health, /while IFS= read -r backup_candidate/, "Sağlık kontrolü devam eden yedeği atlayıp önceki tamamlanmış yedeği aramalı");
  assert.doesNotMatch(health, /sort -nr \| head -n 1/, "Yalnız en yeni klasörü seçmek yedekleme yarışı sırasında yanlış alarm üretir");
  assert.match(healthService, /ReadWritePaths=\/srv\/kozatv\/data/);
  assert.match(restore, /system-restore-test\.json/);
  assert.match(restore, /install -o kozatv -g kozatv -m 0600/);
  assert.match(healthTimer, /OnUnitActiveSec=5m/);
  assert.match(readme, /5432.*açılmaz/);
  assert.match(readme, /DNS değiştirilmeden önce/);
  assert.match(readme, /hedef doluysa işlemi reddeder/i);
  assert.match(readme, /\.github\/workflows\/production\.yml/);
  assert.match(readme, /Eski Hetzner staging sunucusu bu hattın hedefi değildir/);
  assert.match(sshHardening, /^PermitRootLogin no$/m);
  assert.match(sshHardening, /^PasswordAuthentication no$/m);
  assert.match(sshHardening, /^PubkeyAuthentication yes$/m);
  assert.match(sshHardening, /^MaxAuthTries 3$/m);
  assert.match(readme, /00-kozatv-hardening\.conf/);
  assert.match(readme, /passwordauthentication no/);
  assert.match(knownHosts, /^46\.45\.185\.67 ssh-ed25519 [A-Za-z0-9+/=]+\n$/);
});

test("Radore yedekleri sabit sayıda tutulur ve deployment medya arşivini tekrar oluşturmaz", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "kozatv-backup-retention-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const retention = new URL("../deployment/radore/kozatv-backup-retention", import.meta.url).pathname;
  const backup = await readFile(new URL("../deployment/radore/kozatv-postgres-backup", import.meta.url), "utf8");
  const deploy = await readFile(new URL("../deployment/radore/deploy.sh", import.meta.url), "utf8");
  const readme = await readFile(new URL("../deployment/radore/README.md", import.meta.url), "utf8");
  const limits = { "pre-deploy": 3, daily: 7, weekly: 4, monthly: 3 };

  for (const [bucket, keep] of Object.entries(limits)) {
    const directory = join(root, bucket);
    await mkdir(directory, { recursive: true });
    for (let index = 1; index <= keep + 3; index += 1) {
      await mkdir(join(directory, `202609${String(index).padStart(2, "0")}T000000Z`));
    }
    await mkdir(join(directory, "elle-korunan-kurtarma"));
  }

  await execFileAsync("bash", [retention], {
    env: { ...process.env, KOZA_BACKUP_DIR: root, KOZA_BACKUP_TEST_ROOT: root },
  });

  for (const [bucket, keep] of Object.entries(limits)) {
    const entries = (await readdir(join(root, bucket))).sort();
    const automatic = entries.filter((entry) => /^20\d{6}T\d{6}Z$/.test(entry));
    assert.equal(automatic.length, keep, `${bucket} için yalnız son ${keep} otomatik yedek kalmalı`);
    assert.equal(automatic.at(-1), `202609${String(keep + 3).padStart(2, "0")}T000000Z`);
    assert.ok(entries.includes("elle-korunan-kurtarma"), "Elle adlandırılan kurtarma kopyası silinmemeli");
  }

  await assert.rejects(
    execFileAsync("bash", [retention], { env: { ...process.env, KOZA_BACKUP_DIR: join(tmpdir(), "koza-guvensiz-hedef") } }),
    /Güvensiz yedek dizini reddedildi/,
  );

  assert.match(backup, /daily\|--daily/);
  assert.match(backup, /pre-deploy\|--pre-deploy/);
  assert.match(backup, /existing_today/);
  assert.match(backup, /if \[\[ "\$bucket" == "daily" \]\]; then\n\s+tar --create/,
    "Medya yalnız günlük tam yedekte arşivlenmeli");
  assert.match(backup, /cp -al/, "Haftalık ve aylık kopyalar diski tekrar şişirmemeli");
  assert.match(backup, /rsync -aH --delete/, "Uzak kopyada hard-link yapısı korunmalı");
  assert.match(deploy, /kozatv-postgres-backup --pre-deploy/);
  assert.doesNotMatch(deploy, /kozatv-postgres-backup\s*\n/,
    "Deployment tam medya yedeği çalıştırmamalı");
  assert.match(readme, /son \*\*3 deployment veritabanı yedeği\*\*, \*\*7 günlük tam yedek\*\*, \*\*4 haftalık\*\* ve \*\*3 aylık\*\*/);
});

test("Radore uygulama kümesi işlemciyi kullanır ve worker kaybında kontrollü yeniden başlar", async () => {
  const cluster = await readFile(new URL("../scripts/start-cluster.mjs", import.meta.url), "utf8");
  assert.match(cluster, /cluster\.setupPrimary/);
  assert.match(cluster, /Math\.min\(Math\.max/);
  assert.match(cluster, /exits\.length > 10/);
  assert.match(cluster, /worker\?\.disconnect/);
  assert.match(cluster, /SIGTERM/);
});

test("main dağıtımı yalnız Radore üretim adayına gider ve hatada geri döner", async () => {
  const workflow = await readFile(new URL("../.github/workflows/production.yml", import.meta.url), "utf8");
  const deploy = await readFile(new URL("../deployment/radore/deploy.sh", import.meta.url), "utf8");
  const prune = await readFile(new URL("../deployment/radore/prune-releases.sh", import.meta.url), "utf8");
  const sudoers = await readFile(new URL("../deployment/radore/kozatv-deploy.sudoers", import.meta.url), "utf8");

  assert.match(workflow, /name: Koza TV Radore Production/);
  assert.match(workflow, /branches: \[main\]/);
  assert.match(workflow, /environment:\s+name: production/s);
  assert.match(workflow, /secrets\.RADORE_SSH_KEY/);
  assert.match(workflow, /deployment\/radore\/known_hosts/);
  assert.match(workflow, /vars\.KOZA_HOST/);
  assert.match(workflow, /npm audit --omit=dev/);
  assert.match(workflow, /npm test/);
  assert.match(workflow, /npm run lint/);
  assert.match(workflow, /sudo \/usr\/local\/sbin\/kozatv-deploy/);
  assert.doesNotMatch(workflow, /46\.225\.169\.52|HETZNER_SSH_KEY|deployment\/hetzner|staging/i);
  assert.doesNotMatch(workflow, /StrictHostKeyChecking=no/);

  assert.match(deploy, /\^\[0-9a-f\]\{40\}\$/);
  assert.match(deploy, /npm ci/);
  assert.match(deploy, /npm test/);
  assert.match(deploy, /kozatv-postgres-backup/);
  assert.match(deploy, /kozatv-postgres-health/);
  assert.match(deploy, /trap rollback ERR/);
  assert.match(deploy, /mv -Tf/);
  assert.match(deploy, /api\/auth\/me/);
  assert.match(deploy, /KOZA_RELEASE_KEEP_COUNT=4/);
  assert.match(prune, /\^\[0-9a-f\]\{40\}\$/);
  assert.match(prune, /elle oluşturulan geçiş sürümlerine dokunulmadı/);
  assert.match(sudoers, /^koza-deploy ALL=\(root\) NOPASSWD: \/usr\/local\/sbin\/kozatv-deploy \*$/m);
  assert.doesNotMatch(sudoers, /ALL=\(ALL(?::ALL)?\) NOPASSWD: ALL/);
});

test("yük smoke testi sınırlandırılmıştır ve uzak hedefte açık onay ister", async () => {
  const load = await readFile(new URL("../scripts/load-smoke.mjs", import.meta.url), "utf8");
  assert.match(load, /KOZA_ALLOW_REMOTE_LOAD/);
  assert.match(load, /Math\.min\(Math\.max\(Number\(process\.env\.KOZA_LOAD_REQUESTS/);
  assert.match(load, /1000/);
  assert.match(load, /50/);
  assert.match(load, /p95Ms/);
  assert.match(load, /summary\.failures/);
});

test("stage ve üretim aynı sabit font metriklerini kullanır", async () => {
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const bundle = await readFile(new URL("../dist/server/index.js", import.meta.url), "utf8");

  assert.doesNotMatch(layout, /next\/font|Inter\(|Merriweather\(/);
  assert.match(css, /@font-face\{font-family:"Koza Sans";src:local\("Arial"\);ascent-override:90\.44%;descent-override:22\.52%;line-gap-override:0%;size-adjust:107\.12%\}/);
  assert.match(css, /@font-face\{font-family:"Koza Serif";src:local\("Times New Roman"\);ascent-override:80\.59%;descent-override:22\.36%;line-gap-override:0%;size-adjust:122\.09%\}/);
  assert.match(css, /:root\{--font-inter:"Koza Sans";--font-serif:"Koza Serif";/);
  assert.doesNotMatch(bundle, /_vinext_fonts|\.vinext\/fonts/);
  assert.doesNotMatch(bundle, /src: url\(\/(?:Users|home|srv)\/[^)]*\.vinext\/fonts\//);
});
