CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE OR REPLACE FUNCTION koza_search_text(input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$ SELECT replace(lower(unaccent(coalesce(input, ''))), 'ı', 'i') $$;

CREATE TABLE content_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE news_sources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL DEFAULT 'website',
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  last_checked_at BIGINT,
  created_at BIGINT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'other',
  feed_format TEXT NOT NULL DEFAULT 'rss',
  auth_type TEXT NOT NULL DEFAULT 'none',
  secret_env TEXT NOT NULL DEFAULT '',
  poll_interval_minutes INTEGER NOT NULL DEFAULT 15,
  publish_mode TEXT NOT NULL DEFAULT 'review',
  default_category TEXT NOT NULL DEFAULT 'Gündem',
  category_map TEXT NOT NULL DEFAULT '{}',
  disclaimer TEXT NOT NULL DEFAULT '',
  last_success_at BIGINT,
  last_error TEXT NOT NULL DEFAULT '',
  next_poll_at BIGINT,
  updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name CITEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  seo_title TEXT NOT NULL DEFAULT '',
  seo_description TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '#c92721',
  nav_order INTEGER NOT NULL DEFAULT 100,
  is_visible INTEGER NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1)),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE media_assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_key TEXT NOT NULL UNIQUE,
  public_url TEXT NOT NULL UNIQUE,
  original_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  alt_text TEXT NOT NULL DEFAULT '',
  credit TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL
);

CREATE TABLE admin_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email CITEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin','publisher','editor','reporter','viewer')),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  must_change_password INTEGER NOT NULL DEFAULT 1 CHECK (must_change_password IN (0,1)),
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until BIGINT,
  last_login_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE articles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  spot TEXT NOT NULL,
  body TEXT NOT NULL,
  category TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('draft','review','scheduled','published')),
  hero_image TEXT NOT NULL DEFAULT '',
  image_alt TEXT NOT NULL DEFAULT '',
  video_url TEXT NOT NULL DEFAULT '',
  author TEXT NOT NULL DEFAULT 'Koza TV Haber Merkezi',
  source_name TEXT NOT NULL DEFAULT 'Koza TV',
  source_url TEXT NOT NULL DEFAULT '',
  seo_title TEXT NOT NULL DEFAULT '',
  seo_description TEXT NOT NULL DEFAULT '',
  is_breaking INTEGER NOT NULL DEFAULT 0 CHECK (is_breaking IN (0,1)),
  is_featured INTEGER NOT NULL DEFAULT 0 CHECK (is_featured IN (0,1)),
  published_at BIGINT,
  scheduled_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  content_blocks TEXT NOT NULL DEFAULT '[]',
  workflow_state TEXT NOT NULL DEFAULT 'reporter_draft',
  assigned_to INTEGER,
  edit_version INTEGER NOT NULL DEFAULT 1,
  correction_note TEXT NOT NULL DEFAULT '',
  withdrawn_at BIGINT,
  homepage_order INTEGER NOT NULL DEFAULT 100,
  agency_source_id INTEGER REFERENCES news_sources(id),
  agency_external_id TEXT NOT NULL DEFAULT '',
  agency_credit TEXT NOT NULL DEFAULT '',
  agency_received_at BIGINT,
  agency_editorial_lock INTEGER NOT NULL DEFAULT 0 CHECK (agency_editorial_lock IN (0,1)),
  homepage_placement TEXT NOT NULL DEFAULT 'latest' CHECK (homepage_placement IN ('latest','slider','side','below')),
  headline_position TEXT NOT NULL DEFAULT 'left-bottom' CHECK (headline_position IN ('left-top','left-bottom','right-top','right-bottom')),
  is_homepage_gallery INTEGER NOT NULL DEFAULT 0 CHECK (is_homepage_gallery IN (0,1)),
  homepage_latest_at BIGINT,
  body_html TEXT NOT NULL DEFAULT '',
  title_html TEXT NOT NULL DEFAULT '',
  spot_html TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT '',
  updated_by TEXT NOT NULL DEFAULT ''
);

CREATE TABLE admin_sessions (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  user_agent TEXT NOT NULL DEFAULT ''
);

CREATE TABLE article_revisions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  snapshot TEXT NOT NULL,
  actor_id INTEGER,
  actor_name TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  UNIQUE(article_id,version)
);

CREATE TABLE article_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES admin_users(id),
  author_name TEXT NOT NULL,
  body TEXT NOT NULL,
  resolved INTEGER NOT NULL DEFAULT 0 CHECK (resolved IN (0,1)),
  created_at BIGINT NOT NULL
);

CREATE TABLE workflow_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  from_state TEXT NOT NULL,
  to_state TEXT NOT NULL,
  actor_id INTEGER NOT NULL REFERENCES admin_users(id),
  actor_name TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL
);

CREATE TABLE audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  action TEXT NOT NULL,
  actor TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL
);

CREATE TABLE site_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at BIGINT NOT NULL,
  updated_by TEXT NOT NULL DEFAULT ''
);

CREATE TABLE redirects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_path TEXT NOT NULL UNIQUE,
  to_path TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'permanent' CHECK (kind IN ('permanent','temporary')),
  note TEXT NOT NULL DEFAULT '',
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  hits INTEGER NOT NULL DEFAULT 0,
  last_hit_at BIGINT,
  last_check_status INTEGER,
  last_checked_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE import_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_url TEXT NOT NULL UNIQUE,
  source_path TEXT NOT NULL,
  source_lastmod BIGINT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','imported','skipped','failed')),
  article_id INTEGER,
  title TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '',
  discovered_at BIGINT NOT NULL,
  processed_at BIGINT
);

CREATE TABLE agency_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id INTEGER NOT NULL REFERENCES news_sources(id) ON DELETE CASCADE,
  external_id TEXT NOT NULL,
  article_id INTEGER REFERENCES articles(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'published',
  payload_hash TEXT NOT NULL,
  pending_hash TEXT NOT NULL DEFAULT '',
  raw_payload TEXT NOT NULL DEFAULT '',
  source_published_at BIGINT,
  source_updated_at BIGINT,
  received_at BIGINT NOT NULL,
  processed_at BIGINT NOT NULL,
  UNIQUE(source_id, external_id)
);

CREATE TABLE advertisements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placement TEXT NOT NULL CHECK (placement IN ('site_top','site_left_rail','site_right_rail','home_billboard','section_inline','article_sidebar')),
  advertiser TEXT NOT NULL,
  campaign_name TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  target_url TEXT NOT NULL DEFAULT '',
  cta_label TEXT NOT NULL DEFAULT '',
  theme TEXT NOT NULL DEFAULT 'dark' CHECK (theme IN ('red','dark','light')),
  kind TEXT NOT NULL DEFAULT 'direct' CHECK (kind IN ('house','direct','programmatic')),
  priority INTEGER NOT NULL DEFAULT 100 CHECK (priority BETWEEN 1 AND 999),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  starts_at BIGINT,
  ends_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  CHECK (starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at)
);

CREATE INDEX idx_articles_status_published ON articles(status,published_at DESC);
CREATE INDEX idx_articles_category_status ON articles(category,status,published_at DESC);
CREATE INDEX idx_articles_featured ON articles(is_featured,status,published_at DESC) WHERE is_featured=1;
CREATE INDEX idx_articles_homepage_placement ON articles(homepage_placement,status,homepage_order,published_at DESC);
CREATE INDEX idx_articles_homepage_gallery ON articles(is_homepage_gallery,status,published_at DESC) WHERE is_homepage_gallery=1;
CREATE INDEX idx_articles_homepage_latest ON articles(status,homepage_placement,COALESCE(homepage_latest_at,published_at,updated_at) DESC,id DESC);
CREATE INDEX idx_articles_homepage_latest_clock ON articles(homepage_latest_at DESC);
CREATE UNIQUE INDEX idx_articles_agency_identity ON articles(agency_source_id,agency_external_id) WHERE agency_source_id IS NOT NULL AND agency_external_id<>'';
CREATE INDEX idx_workflow_state_assignee ON articles(workflow_state,assigned_to,updated_at DESC);
CREATE INDEX idx_categories_visible_order ON categories(is_visible,nav_order,name);
CREATE INDEX idx_media_assets_created ON media_assets(created_at DESC);
CREATE INDEX idx_media_assets_type_created ON media_assets(mime_type,created_at DESC);
CREATE INDEX idx_admin_sessions_user_expiry ON admin_sessions(user_id,expires_at);
CREATE INDEX idx_admin_sessions_expiry ON admin_sessions(expires_at);
CREATE INDEX idx_revisions_article_version ON article_revisions(article_id,version DESC);
CREATE INDEX idx_comments_article_created ON article_comments(article_id,created_at DESC);
CREATE INDEX idx_workflow_events_article ON workflow_events(article_id,created_at DESC);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type,entity_id,created_at DESC);
CREATE INDEX idx_redirects_active ON redirects(active,from_path);
CREATE INDEX idx_import_items_status ON import_items(status,source_lastmod DESC);
CREATE INDEX idx_agency_items_source_received ON agency_items(source_id,received_at DESC);
CREATE INDEX idx_advertisements_delivery ON advertisements(placement,active,priority DESC,starts_at,ends_at);
