export const seedArticles = [
  { slug: "turkiyenin-gundemi-koza-tv-haber-merkezinde", title: "Türkiye'nin gündemi Koza TV Haber Merkezi'nde", spot: "Sahadan canlı bağlantılar, doğrulanmış bilgiler ve uzman görüşleriyle günün bütün gelişmeleri Koza TV ekranında.", body: "Koza TV Haber Merkezi, Türkiye ve dünyadaki gelişmeleri gün boyunca canlı bağlantılar ve doğrulanmış bilgilerle izleyiciye aktarıyor.\n\nMuhabirlerimiz karar merkezlerinden, meydanlardan ve yaşamın içinden gelişmeleri aktarırken; uzman konuklar haberlerin arka planını ve olası etkilerini değerlendiriyor.\n\nGünün öne çıkan başlıkları Koza TV televizyon yayını, internet sitesi ve dijital kanallarda eş zamanlı olarak izlenebiliyor.", category: "Gündem", status: "published", heroImage: "/news/gundem.jpg", imageAlt: "Koza TV gündem haberleri", author: "Koza TV Haber Merkezi", sourceName: "Koza TV", sourceUrl: "", isBreaking: 1, isFeatured: 1, publishedOffsetMinutes: 8 },
  { slug: "karar-merkezlerinde-yogun-trafik", title: "Karar merkezlerinde yoğun trafik: Kritik başlıklar masada", spot: "Ankara'daki görüşmelerin gündemi ve ilk açıklamalar Koza TV muhabirlerinin aktarımıyla.", body: "Başkentte gün boyu süren görüşmelerde ekonomi, dış politika ve Meclis gündemi ele alındı.\n\nKoza TV Ankara ekibi, toplantılardan yansıyan mesajları ve kulislerde konuşulan başlıkları doğrulama sürecinden geçirerek aktarıyor.", category: "Siyaset", status: "published", heroImage: "/news/politika.jpg", imageAlt: "Ankara'da siyasi gündem", author: "Ankara Haber Merkezi", sourceName: "Koza TV", sourceUrl: "", isBreaking: 0, isFeatured: 1, publishedOffsetMinutes: 24 },
  { slug: "piyasalar-yeni-karara-odaklandi", title: "Piyasalar yeni karara odaklandı: Ekonomistler ne bekliyor?", spot: "Para piyasalarında haftanın kritik verileri öncesinde temkinli seyir öne çıkıyor.", body: "Piyasalarda yeni haftanın veri gündemi yakından takip ediliyor. Ekonomistler kararın fiyatlama davranışları ve yatırım eğilimleri üzerindeki etkisini değerlendiriyor.\n\nKoza TV Ekonomi Servisi, güncel verileri teyit edilmiş kaynaklardan izleyerek okura anlaşılır bir çerçevede sunuyor.", category: "Ekonomi", status: "published", heroImage: "/news/ekonomi.jpg", imageAlt: "Ekonomi ve piyasa göstergeleri", author: "Koza TV Ekonomi Servisi", sourceName: "Koza TV", sourceUrl: "", isBreaking: 0, isFeatured: 1, publishedOffsetMinutes: 38 },
  { slug: "diplomasi-trafigi-hizlandi-kritik-zirve", title: "Diplomasi trafiği hızlandı: Kritik zirveden ilk mesajlar", spot: "Liderlerin görüşmesinde bölgesel güvenlik, ticaret ve insani yardım başlıkları ele alındı.", body: "Uluslararası zirvede bölgesel gelişmeler ve yeni iş birliği alanları masaya yatırıldı.\n\nKoza TV Dünya Servisi, resmi açıklamalar ve sahadaki muhabirlerden gelen bilgileri karşılaştırarak gelişmeleri aktarıyor.", category: "Dünya", status: "published", heroImage: "/news/dunya.jpg", imageAlt: "Uluslararası diplomasi zirvesi", author: "Koza TV Dünya Servisi", sourceName: "Koza TV", sourceUrl: "", isBreaking: 0, isFeatured: 0, publishedOffsetMinutes: 52 },
  { slug: "milli-takim-kadrosu-aciklandi", title: "Milli takımın yeni dönem kadrosu açıklandı", spot: "Teknik ekip, yaklaşan karşılaşmalar öncesinde aday kadroyu kamuoyuyla paylaştı.", body: "Milli takımın hazırlık programı ve aday kadrosu açıklandı. Takım, ilk çalışmasını hafta içinde gerçekleştirecek.\n\nKoza TV Spor Servisi karşılaşma programını ve kamp gelişmelerini anlık olarak takip edecek.", category: "Spor", status: "published", heroImage: "/news/studio.jpg", imageAlt: "Koza TV spor yayını", author: "Koza TV Spor Servisi", sourceName: "Koza TV", sourceUrl: "", isBreaking: 0, isFeatured: 0, publishedOffsetMinutes: 74 },
  { slug: "meteorolojiden-kuvvetli-yagis-uyarisi", title: "Meteoroloji'den kuvvetli yağış uyarısı", spot: "Bazı bölgelerde beklenen yağış nedeniyle ulaşımda aksama ve su baskını riskine karşı dikkat çağrısı yapıldı.", body: "Meteoroloji değerlendirmelerine göre yağışların yerel olarak kuvvetli olması bekleniyor.\n\nVatandaşların resmi uyarıları takip etmesi ve riskli bölgelerde tedbirli olması istendi.", category: "Yaşam", status: "published", heroImage: "/news/gundem.jpg", imageAlt: "Yağışlı hava ve meteoroloji uyarısı", author: "Koza TV Haber Merkezi", sourceName: "Meteoroloji Genel Müdürlüğü", sourceUrl: "https://www.mgm.gov.tr/", isBreaking: 0, isFeatured: 0, publishedOffsetMinutes: 96 },
  { slug: "editor-kontrolunde-yapay-zeka-haber-masasi", title: "Editör kontrolünde yapay zekâ destekli haber masası", spot: "Kaynak tarama ve taslak hazırlama süreçleri hızlanırken son yayın kararı daima editörde kalıyor.", body: "Koza TV'nin yeni yayın altyapısında kaynaklar otomatik olarak izlenebilecek ve gelişmeler editör kuyruğuna taslak halinde taşınacak.\n\nTelif, doğrulama, görsel ve kaynak kontrolleri tamamlanmadan hiçbir yapay zekâ taslağı yayına alınmayacak.", category: "Teknoloji", status: "review", heroImage: "/news/studio.jpg", imageAlt: "Koza TV dijital haber masası", author: "Dijital Yayınlar", sourceName: "Koza TV", sourceUrl: "", isBreaking: 0, isFeatured: 0, publishedOffsetMinutes: 0 },
] as const;

export const seedSources = [
  { name: "Resmî Gazete", url: "https://www.resmigazete.gov.tr/", type: "official" },
  { name: "Meteoroloji Genel Müdürlüğü", url: "https://www.mgm.gov.tr/", type: "official" },
  { name: "AFAD", url: "https://www.afad.gov.tr/", type: "official" },
  { name: "TCMB", url: "https://www.tcmb.gov.tr/", type: "official" },
];
